admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

clien:
    resource: "@ClienBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
